### ISSUE TITLE
proto file with double quotes at the end of the message field comment is generated with a syntax error

### ISSUE THREAD

**Issue by efpato** [dropbox/mypy-protobuf#296] opened 2021-09-22 04:02 UTC
message.proto
```proto
syntax = "proto3";

package message;

message Message {
  // Field "One".
  string field1 = 1;
  // Field "Two"
  string field2 = 2;
}
```

message_pb2.pyi
```python
...
class Message(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    FIELD1_FIELD_NUMBER: builtins.int
    FIELD2_FIELD_NUMBER: builtins.int
    field1: typing.Text = ...
    """Field "One"."""

    field2: typing.Text = ...
    """Field "Two""""  <-- [mypy error] EOL while scanning string literal
...
```

**Comment by sodul** [comment] 2021-09-22 22:39
The issue is that the comments from the proto files are entered as string declarations. This is really not a good idea to do that, comments should be comments and have a `#` in front of them.

This is causing a lot of breakage with out own proto files.

**Comment by sodul** [comment] 2021-09-22 22:45
@nipunn1313  @jaredkhan can you please revert #281. While this comes from a good idea it breaks code generation under different conditions, namely if the comment starts or ends with `"`, and maybe (have not checked) if the comment ends with `\`.

This is a big regression and I am not a big fan of abusing string declarations as comments, since they can cause further unexpected side effects, even though this use is approved by Guido.

**Comment by jaredkhan** [comment] 2021-09-25 15:34
Good points, thanks for raising both. The docstring functionality added is quite useful and so I think it's worth considering how we can get it working without these issues.

The important things are:
- to make sure the triple quotes aren't interfered with
- to make sure the string itself doesn't contain syntax errors such as invalid escape sequences

I think the following PR gets most of the way to escaping what needs to be escaped without sacrificing the accessibility of the documentation:
https://github.com/dropbox/mypy-protobuf/pull/297/files
Feel free to give that a try and see if it works for you or have a read to see if you can spot other issues.

Overall, it's of course up to @nipunn1313 what approach to take

**Comment by sodul** [comment] 2021-09-26 01:55
I have to point out that there is a difference between a docstring, which I fully encourage, and a string declaration used as a comment.

For example:
```
class Foo:
    """This is the docstring for Foo."""  # A docstring

    """Comment about bar."""  # anonymous string declaration
    bar = "value for bar"
    """Comment about baz."""  # anonymous string declaration
    baz = "value for baz"
    my_dict = {
        """Comment about Bob:"""  # string declaration, will be joined
        'bob': 'secret for bob',
        """Comment about Alice:"""  # string declaration, will be joined.
        'alice': 'secret for alice'
    }
```
Paste that in a python REPL, and check the values:
```
>>> Foo.__doc__
'This is the docstring for Foo.'

>>> Foo.bar
'value for bar'

>>> Foo.baz
'value for baz'

>>> Foo.my_dict
{'Comment about Bob:bob': 'secret for bob', 'Comment about Alice:alice': 'secret for Alice'}
```

Notice how the 'comments' in the dictionary got appended with the keys, completely ruining the actual code.
While anonymous string declarations are indeed ignored by the compiler as comments, they increase the confusion between a docstring, a comment, and the fact that strings get implicitly joined even across multiple lines when on a multiline statement. Since there is no longer visual difference in coloring between a string declaration and a comment in most IDEs (do some make the difference between an anonymous string declaration and a real string declaration?) this can lead to unexpected behavior as demonstrated about.

As such I personally strongly recommend against anonymous string declarations as comments. I recommend that you do keep the docstring, they are good, but for the other cases I prefer that comments remain comments. At the very least give us the option to not use anonymous string declarations.

Notes:
*  I use the term `anonymous string declaration` but I do not know if it is an official term.
* For others that might be less familiar with python strings, there is nothing special about `"""` making it a string or a docstring. It is always used for docstring just by convention in PEP-8, but a docstring is just a string declared as the first statement inside an object and gets assigned to `__doc__` automatically. Any string can use `"""`, `'''`, `"`, or `'` and still behave the same (mostly). They are just various delimiters for strings, or multiline strings, declarations.

**Comment by nipunn1313** [comment] 2021-09-26 17:22
Hey everyone. I really appreciate this report and the discussion and the attempt in #297 This certainly is a bug, and we can't tolerate generating broken stubs.

Seeing a lot of contention - going to try and break down into the expressed individual goals and assign priorities to try and come up with a good solution

# Goals

- Generating correct stubs without syntax errors (P0)
- Working IDE documentation (P1)
- Avoid flags to mypy-protobuf (P1) - unless strictly necessary, flags tend to be high maintenance - and often doesn't actually address the underlying issue. Only use if necessary.
- Prefer `#` comments to `"""` for aesthetic (P2)
- Correct docstring usage per python spec (P3 - since `__doc__` isn't relevant for stubs)
- Runtime overhead from parsing strings (P3 - since only in stub files)

# Concerns/Ideas
- Current generated code has syntax errors. This is unacceptable. Will have to fix somehow.
- This type of string-comment will fail
```
    my_dict = {
        """Comment about Bob:"""  # string declaration, will be joined
        'bob': 'secret for bob',
        """Comment about Alice:"""  # string declaration, will be joined.
        'alice': '''secret for alice'''
    }
```
I don't believe that mypy-protobuf generates any of these, but will double check.
- Idea: use `repr` because it's guaranteed to produce a parseable item while minimizing logic in mypy-protobuf

# Action Items

- Check to see if pycharm IDE will display `#` comments on inner variables - or if it needs to be a string comment per https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring. Prefer `#` if possible, but use string comments if needed.
- Try out `repr` for string comments using test cases from #297 
- Release mypy-protobuf 3.0.0 w/ the fixes

Again super appreciate all of you for finding this issue and reporting it. If you're running into it for now, use an older release (`pip install mypy_protobuf==2.9`) of mypy-protobuf.

**Closed** 2021-09-28 17:45 UTC
